# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-15 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_text', models.CharField(max_length=200)),
                ('wish_image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
